In [1]:
import numpy as np
import pandas as pd

In [3]:
credit_card_ds = pd.read_csv('credit_data.csv')
credit_card_ds.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
# No missing values in this ds
credit_card_ds.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
# imbalanced data
credit_card_ds['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

0 -> Legit Transactions
1 -> Fraudulant Transactions

In [6]:
# separating the data
legit = credit_card_ds[credit_card_ds.Class == 0]
fraud = credit_card_ds[credit_card_ds.Class == 1]
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [7]:
legit_sample = legit.sample(n = 492)
print(legit_sample.shape)

(492, 31)

In [8]:
new_df = pd.concat([legit_sample, fraud], axis = 0)
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279539,168931.0,2.043660,-0.031041,-1.155157,0.214705,0.164821,-0.681174,0.146086,-0.227463,0.143470,...,-0.246711,-0.558488,0.276001,-0.307023,-0.249827,0.194798,-0.067952,-0.071169,1.29,0
58121,48240.0,1.324200,-0.345892,0.174443,-0.567806,-0.761472,-0.712726,-0.558041,-0.061349,-0.800961,...,-0.112000,-0.434425,0.135343,-0.020544,0.152934,-0.451628,0.035232,0.042888,25.00,0
218093,141167.0,-0.839574,1.254793,0.265456,-0.542531,0.310901,-0.709494,0.755939,0.151356,-0.027911,...,-0.043797,0.028981,-0.059796,1.010284,-0.339463,0.301829,-0.066521,-0.048787,32.00,0
27600,34619.0,1.164911,-0.678003,-0.007276,-0.489296,-0.764045,-0.277657,-0.594831,0.110148,-0.789368,...,0.033285,-0.077683,-0.048301,-0.059485,0.324127,-0.294297,0.016605,0.035369,83.16,0
206084,136059.0,-0.385766,0.737561,0.580338,-0.804500,0.900553,-0.401196,1.466679,-0.430917,-0.063618,...,-0.262621,-0.567259,-0.247690,-0.708186,-0.088887,0.289610,-0.239780,-0.110796,45.47,0